version: '3.8'

services:
  db:
    image: postgres:15.2-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
#     networks:
#       - app_network
#   api:
#     container_name: api
#     build:
#       context: .
#       dockerfile: ./apps/api/Dockerfile
#     restart: always
#     ports:
#       - 3000:3000
#     networks:
#       - app_network
# volumes:
#   postgres-data:


# networks:
#   app_network:
#     driver: bridge
